# Generated by Django 5.1.7 on 2025-03-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.CharField(default='P-573862725', max_length=11),
        ),
    ]
