# Generated by Django 5.1.7 on 2025-03-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.CharField(max_length=11),
        ),
    ]
