# Generated by Django 5.1.7 on 2025-03-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_end_date_project_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
