# Generated by Django 5.1.7 on 2025-03-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_project_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(),
        ),
    ]
